# Generated by Django 5.0.3 on 2024-09-14 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('topico', models.CharField(max_length=100)),
                ('qtd_perguntas', models.IntegerField()),
                ('tempo', models.IntegerField(help_text='Duração do teste em minutos')),
                ('texto', models.CharField(max_length=300)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('funcionarios', models.ManyToManyField(blank=True, to='empresas.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('qtd_respostas', models.IntegerField(default=4)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formularios2.categoria')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.formulario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('resposta_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.questao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_formulario', models.CharField(max_length=50)),
                ('pontuacao', models.FloatField()),
                ('frase', models.CharField(max_length=500)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.formulario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.funcionario')),
            ],
        ),
    ]
