# Generated by Django 5.0.3 on 2024-04-15 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('topico', models.CharField(max_length=100)),
                ('qtd_perguntas', models.IntegerField()),
                ('qtd_acertos', models.IntegerField(help_text='Pontuação realizada pelo usuário')),
                ('tempo', models.IntegerField(help_text='Duração do teste em minutos')),
                ('texto', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('qtd_respostas', models.IntegerField(default=4)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.categoria')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.formulario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('resposta_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.questao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
