# Generated by Django 5.0.3 on 2024-05-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='qtd_acertos',
        ),
        migrations.AlterField(
            model_name='resultado',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios2.formulario'),
        ),
    ]
