# Generated by Django 5.0.3 on 2024-05-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formularios2.categoria'),
        ),
    ]
