# Generated by Django 5.0.3 on 2024-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('formularios2', '0002_formulario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='formularios',
            field=models.ManyToManyField(blank=True, related_name='formularios', to='empresas.funcionario'),
        ),
    ]
