# Generated by Django 5.0.3 on 2024-07-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios2', '0003_formulario_formularios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='formularios',
            new_name='funcionarios',
        ),
    ]
