# Generated by Django 5.0.3 on 2024-07-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios2', '0006_remove_formulario_texto_formulario_textoteste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='textoteste',
            new_name='texto',
        ),
    ]
