# Generated by Django 5.0.3 on 2024-03-31 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.BooleanField(default=False)),
                ('razao_social', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('setor', models.CharField(choices=[('V', 'Varejo'), ('A', 'Atacado'), ('S', 'Serviço'), ('T', 'Tecnologia'), ('I', 'Industria'), ('Outro', 'Outro')], max_length=10)),
                ('qtd_vendedores', models.CharField(choices=[('1-5', 'De 01 a 05'), ('6-10', 'De 06 a 10'), ('11-15', 'De 11 a 15'), ('16-30', 'De 16 a 30'), ('30+', 'Acima de 30')], max_length=10)),
                ('cargo', models.CharField(choices=[('S', 'Sócio/Proprietário'), ('CEO', 'CEO'), ('GC', 'Gestor Comercial'), ('GR', 'Gestor RH'), ('BP', 'Bussiness Partner RH'), ('V', 'Vendedor')], max_length=10)),
                ('telefone', models.CharField(max_length=11)),
                ('segmento', models.CharField(choices=[('A', 'Alimentação'), ('T', 'Transporte'), ('Cons', 'Consultoria'), ('V', 'Vestuário'), ('PE', 'Peças e Equipamentos'), ('M', 'Manutenção'), ('Q', 'Química'), ('F', 'Farmaceutica'), ('Cosm', 'Cosmético'), ('E', 'Educação'), ('O', 'Outro')], max_length=10)),
                ('senha', models.CharField(max_length=100)),
                ('repetir_senha', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=8)),
                ('CNPJ', models.CharField(max_length=11)),
                ('endereco_cobranca', models.CharField(max_length=100)),
                ('contato_financeiro', models.CharField(max_length=100)),
                ('telefone_financeiro', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(choices=[('', '')], max_length=10)),
                ('telefone', models.CharField(max_length=11)),
                ('status_questionario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='painel.status')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(choices=[('', '')], max_length=10)),
                ('telefone', models.CharField(max_length=11)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.empresa')),
                ('status_questionario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='painel.status')),
            ],
        ),
    ]
