# Generated by Django 5.0.3 on 2024-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='funcao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(max_length=10),
        ),
    ]
